version: '3.3'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "data:/var/lib/mysql"
      - "data:/var/log/mysql"
      - "./mysql:/etc/mysql/conf.d"
      - "./mysql/init:/docker-entrypoint-initdb.d"
      - "./mysql/log:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "password"

volumes:
  data: